language: java

env:
   global:
        - secure: "OkFYNXvPgdRGL3juvdPyLWaDIwjxEgU7/aTxWC5DsSiTQVk8DyStZcfL8aquhlq6lcZpPReWgqQMyjHBK+hJ/FQ47+WqgbD5HLuFR5dWpaLWH7oSxjEtbER4JlhktMFJCGXyuCgnvdlEKAfBBjgm7jx9XhngkGv7yW3af23kU60="
        - secure: "MzTquHmCRU0gVRo1IdigsfJy95tVslsw7CU2/MpCBCcpPGPmZOL2Cu8tFpH+DfHPniEd0hkaGQts9aDCf04fdeG8w5gxN80317i0obFYW7Isynw6djrd0M9I52fNdtdgwTbpYbnoenKCizjCnDdE0wquS8acQ+QPH2O3EHcZG9A="

addons:
  coverity_scan:
    project:
      name: "lyncode/jtwig"
      description: "Build submitted via Travis CI"
    notification_email: jmelo@lyncode.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

after_success:
  - mvn compile -Pmerge-reports -N
  - mvn coveralls:report