language: java

env:
   global:
        - secure: "JI6RwImFT05GUsoBY4D1PWZPkmdsZ34xkWVVm2HMmZpvURUmeHpUyVZw1o5bZE2UpfVPCIj9/z94Zo6o+lhXO0KY2qDr1KOFZUuJWU/B74zUL+bRUqb0A2XK3h4u+a/eeESL74gCsHtzaiMIZ6v6UEyNu8jywSs3B+PiKetrbfU="
        - secure: ﻿"Oi3OdgwgSJ4TQYWkyAKG0OzI5NOfajwWE+7uoZv5drKlkD5MKhk8OkGavOBIDo2uwJcspErSqmUJDyR5Yyz6CTCpRY/5n6emRohh2KAYS/pMdTv+eX8nSXB3K/Uov+e5W8lt0nRgUxzsiyQMOy3cTpprA5224k/RLTviGsV+Tbg="
        - secure: ﻿"Ju9O6URnKo4SoKKnKFiIwITjfwmoAWURut5ou9UULKD412eh0VoyGPg+P3vBRRk2pjgEofRo9fxiX9hMkJyINTM8c8m+X8wJCSBEigFFcCALsQSvWzW3OCoMcfKh/nijvI05S4HNOE5hI0E/Qx8AJBhkzhXEMoUFDmn6WwrkB0s="


after_success:
  - gradle bintrayUpload tagRelease
  - mvn install
  - mvn compile -Pmerge-reports -N
  - mvn coveralls:report
  
notifications:
  slack: jtwig:BHkhGZvVL7Bsg6HhoY0A3CZu
